# This workflow will run tests using node and then publish a package to GitHub Packages when package.json version is updated on main
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: Test and Release
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
  release:
    types: [created]
jobs:
  check-version-change:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    outputs:
      should_run: ${{ steps.check.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - id: check
        name: Check if version changed
        run: |
          git diff HEAD^ HEAD -- package.json | grep -q '"version":' && echo "changed=true" >> $GITHUB_OUTPUT || echo "changed=false" >> $GITHUB_OUTPUT
  
  test:
    needs: [check-version-change]
    if: github.event_name == 'release' || needs.check-version-change.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run test
      - run: npm run tsc
      - run: npm run lint
  
  publish:
    runs-on: ubuntu-latest
    needs: [test, check-version-change]
    if: github.event_name == 'release' || needs.check-version-change.outputs.should_run == 'true'
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public
